// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "All.hpp"

#include "IClientShell.hpp"
#include "ICommandLineArgs.hpp"
#include "ICompress.hpp"
#include "ILTClient.hpp"
#include "ILTClientContentTransfer.hpp"
#include "ILTCommon.hpp"
#include "ILTCursor.hpp"
#include "ILTCustomRender.hpp"
#include "ILTDrawPrim.hpp"
#include "ILTFileMgr.hpp"
#include "ILTInput.hpp"
#include "ILTLoadingProgress.hpp"
#include "ILTModel.hpp"
#include "ILTPhysics.hpp"
#include "ILTPhysicsSim.hpp"
#include "ILTRenderer.hpp"
#include "ILTResourceMgr.hpp"
#include "ILTServer.hpp"
#include "ILTServerContentTransfer.hpp"
#include "ILTSoundMgr.hpp"
#include "ILTTextureMgr.hpp"
#include "ILTTextureString.hpp"
#include "ILTTimer.hpp"
#include "ILTUI.hpp"
#include "ILTVideoTexture.hpp"
#include "IServerConsoleState.hpp"
#include "IServerShell.hpp"
#include "IWorldClientBSP.hpp"
#include "IWorldParticleBlockerData.hpp"
#include "IWorldServerBSP.hpp"

namespace sdk::interfaces {

namespace {

void* get_IClientShell_Default() { return IClientShell::get(); }
Registry::Agreement agree_IClientShell_Default() { return IClientShell::agreement(); }

void* get_ICommandLineArgs_Default() { return ICommandLineArgs::get(); }
Registry::Agreement agree_ICommandLineArgs_Default() { return ICommandLineArgs::agreement(); }

void* get_ICompress_Default() { return ICompress::get(); }
Registry::Agreement agree_ICompress_Default() { return ICompress::agreement(); }

void* get_ILTClient_Default() { return ILTClient::get(); }
Registry::Agreement agree_ILTClient_Default() { return ILTClient::agreement(); }

void* get_ILTClientContentTransfer_Default() { return ILTClientContentTransfer::get(); }
Registry::Agreement agree_ILTClientContentTransfer_Default() { return ILTClientContentTransfer::agreement(); }

void* get_ILTCommon_Client() { return ILTCommon::get_client(); }
Registry::Agreement agree_ILTCommon_Client() { return ILTCommon::agreement_client(); }

void* get_ILTCommon_Server() { return ILTCommon::get_server(); }
Registry::Agreement agree_ILTCommon_Server() { return ILTCommon::agreement_server(); }

void* get_ILTCursor_Default() { return ILTCursor::get(); }
Registry::Agreement agree_ILTCursor_Default() { return ILTCursor::agreement(); }

void* get_ILTCustomRender_Default() { return ILTCustomRender::get(); }
Registry::Agreement agree_ILTCustomRender_Default() { return ILTCustomRender::agreement(); }

void* get_ILTDrawPrim_Default() { return ILTDrawPrim::get(); }
Registry::Agreement agree_ILTDrawPrim_Default() { return ILTDrawPrim::agreement(); }

void* get_ILTFileMgr_Default() { return ILTFileMgr::get(); }
Registry::Agreement agree_ILTFileMgr_Default() { return ILTFileMgr::agreement(); }

void* get_ILTInput_Default() { return ILTInput::get(); }
Registry::Agreement agree_ILTInput_Default() { return ILTInput::agreement(); }

void* get_ILTLoadingProgress_Default() { return ILTLoadingProgress::get(); }
Registry::Agreement agree_ILTLoadingProgress_Default() { return ILTLoadingProgress::agreement(); }

void* get_ILTModel_Client() { return ILTModel::get_client(); }
Registry::Agreement agree_ILTModel_Client() { return ILTModel::agreement_client(); }

void* get_ILTModel_Server() { return ILTModel::get_server(); }
Registry::Agreement agree_ILTModel_Server() { return ILTModel::agreement_server(); }

void* get_ILTPhysics_Client() { return ILTPhysics::get_client(); }
Registry::Agreement agree_ILTPhysics_Client() { return ILTPhysics::agreement_client(); }

void* get_ILTPhysics_Server() { return ILTPhysics::get_server(); }
Registry::Agreement agree_ILTPhysics_Server() { return ILTPhysics::agreement_server(); }

void* get_ILTPhysicsSim_Client() { return ILTPhysicsSim::get_client(); }
Registry::Agreement agree_ILTPhysicsSim_Client() { return ILTPhysicsSim::agreement_client(); }

void* get_ILTPhysicsSim_Server() { return ILTPhysicsSim::get_server(); }
Registry::Agreement agree_ILTPhysicsSim_Server() { return ILTPhysicsSim::agreement_server(); }

void* get_ILTRenderer_Default() { return ILTRenderer::get(); }
Registry::Agreement agree_ILTRenderer_Default() { return ILTRenderer::agreement(); }

void* get_ILTResourceMgr_Default() { return ILTResourceMgr::get(); }
Registry::Agreement agree_ILTResourceMgr_Default() { return ILTResourceMgr::agreement(); }

void* get_ILTServer_Default() { return ILTServer::get(); }
Registry::Agreement agree_ILTServer_Default() { return ILTServer::agreement(); }

void* get_ILTServerContentTransfer_Default() { return ILTServerContentTransfer::get(); }
Registry::Agreement agree_ILTServerContentTransfer_Default() { return ILTServerContentTransfer::agreement(); }

void* get_ILTSoundMgr_Client() { return ILTSoundMgr::get_client(); }
Registry::Agreement agree_ILTSoundMgr_Client() { return ILTSoundMgr::agreement_client(); }

void* get_ILTSoundMgr_Server() { return ILTSoundMgr::get_server(); }
Registry::Agreement agree_ILTSoundMgr_Server() { return ILTSoundMgr::agreement_server(); }

void* get_ILTTextureMgr_Default() { return ILTTextureMgr::get(); }
Registry::Agreement agree_ILTTextureMgr_Default() { return ILTTextureMgr::agreement(); }

void* get_ILTTextureString_Default() { return ILTTextureString::get(); }
Registry::Agreement agree_ILTTextureString_Default() { return ILTTextureString::agreement(); }

void* get_ILTTimer_Client() { return ILTTimer::get_client(); }
Registry::Agreement agree_ILTTimer_Client() { return ILTTimer::agreement_client(); }

void* get_ILTTimer_Server() { return ILTTimer::get_server(); }
Registry::Agreement agree_ILTTimer_Server() { return ILTTimer::agreement_server(); }

void* get_ILTUI_Default() { return ILTUI::get(); }
Registry::Agreement agree_ILTUI_Default() { return ILTUI::agreement(); }

void* get_ILTVideoTexture_Default() { return ILTVideoTexture::get(); }
Registry::Agreement agree_ILTVideoTexture_Default() { return ILTVideoTexture::agreement(); }

void* get_IServerConsoleState_Default() { return IServerConsoleState::get(); }
Registry::Agreement agree_IServerConsoleState_Default() { return IServerConsoleState::agreement(); }

void* get_IServerShell_Default() { return IServerShell::get(); }
Registry::Agreement agree_IServerShell_Default() { return IServerShell::agreement(); }

void* get_IWorldClientBSP_Default() { return IWorldClientBSP::get(); }
Registry::Agreement agree_IWorldClientBSP_Default() { return IWorldClientBSP::agreement(); }

void* get_IWorldParticleBlockerData_Default() { return IWorldParticleBlockerData::get(); }
Registry::Agreement agree_IWorldParticleBlockerData_Default() { return IWorldParticleBlockerData::agreement(); }

void* get_IWorldServerBSP_Default() { return IWorldServerBSP::get(); }
Registry::Agreement agree_IWorldServerBSP_Default() { return IWorldServerBSP::agreement(); }

const InterfaceEntry kAll[] = {
    {"IClientShell.Default", &get_IClientShell_Default, &agree_IClientShell_Default},
    {"ICommandLineArgs.Default", &get_ICommandLineArgs_Default, &agree_ICommandLineArgs_Default},
    {"ICompress.Default", &get_ICompress_Default, &agree_ICompress_Default},
    {"ILTClient.Default", &get_ILTClient_Default, &agree_ILTClient_Default},
    {"ILTClientContentTransfer.Default", &get_ILTClientContentTransfer_Default, &agree_ILTClientContentTransfer_Default},
    {"ILTCommon.Client", &get_ILTCommon_Client, &agree_ILTCommon_Client},
    {"ILTCommon.Server", &get_ILTCommon_Server, &agree_ILTCommon_Server},
    {"ILTCursor.Default", &get_ILTCursor_Default, &agree_ILTCursor_Default},
    {"ILTCustomRender.Default", &get_ILTCustomRender_Default, &agree_ILTCustomRender_Default},
    {"ILTDrawPrim.Default", &get_ILTDrawPrim_Default, &agree_ILTDrawPrim_Default},
    {"ILTFileMgr.Default", &get_ILTFileMgr_Default, &agree_ILTFileMgr_Default},
    {"ILTInput.Default", &get_ILTInput_Default, &agree_ILTInput_Default},
    {"ILTLoadingProgress.Default", &get_ILTLoadingProgress_Default, &agree_ILTLoadingProgress_Default},
    {"ILTModel.Client", &get_ILTModel_Client, &agree_ILTModel_Client},
    {"ILTModel.Server", &get_ILTModel_Server, &agree_ILTModel_Server},
    {"ILTPhysics.Client", &get_ILTPhysics_Client, &agree_ILTPhysics_Client},
    {"ILTPhysics.Server", &get_ILTPhysics_Server, &agree_ILTPhysics_Server},
    {"ILTPhysicsSim.Client", &get_ILTPhysicsSim_Client, &agree_ILTPhysicsSim_Client},
    {"ILTPhysicsSim.Server", &get_ILTPhysicsSim_Server, &agree_ILTPhysicsSim_Server},
    {"ILTRenderer.Default", &get_ILTRenderer_Default, &agree_ILTRenderer_Default},
    {"ILTResourceMgr.Default", &get_ILTResourceMgr_Default, &agree_ILTResourceMgr_Default},
    {"ILTServer.Default", &get_ILTServer_Default, &agree_ILTServer_Default},
    {"ILTServerContentTransfer.Default", &get_ILTServerContentTransfer_Default, &agree_ILTServerContentTransfer_Default},
    {"ILTSoundMgr.Client", &get_ILTSoundMgr_Client, &agree_ILTSoundMgr_Client},
    {"ILTSoundMgr.Server", &get_ILTSoundMgr_Server, &agree_ILTSoundMgr_Server},
    {"ILTTextureMgr.Default", &get_ILTTextureMgr_Default, &agree_ILTTextureMgr_Default},
    {"ILTTextureString.Default", &get_ILTTextureString_Default, &agree_ILTTextureString_Default},
    {"ILTTimer.Client", &get_ILTTimer_Client, &agree_ILTTimer_Client},
    {"ILTTimer.Server", &get_ILTTimer_Server, &agree_ILTTimer_Server},
    {"ILTUI.Default", &get_ILTUI_Default, &agree_ILTUI_Default},
    {"ILTVideoTexture.Default", &get_ILTVideoTexture_Default, &agree_ILTVideoTexture_Default},
    {"IServerConsoleState.Default", &get_IServerConsoleState_Default, &agree_IServerConsoleState_Default},
    {"IServerShell.Default", &get_IServerShell_Default, &agree_IServerShell_Default},
    {"IWorldClientBSP.Default", &get_IWorldClientBSP_Default, &agree_IWorldClientBSP_Default},
    {"IWorldParticleBlockerData.Default", &get_IWorldParticleBlockerData_Default, &agree_IWorldParticleBlockerData_Default},
    {"IWorldServerBSP.Default", &get_IWorldServerBSP_Default, &agree_IWorldServerBSP_Default},
};

} // namespace

const InterfaceEntry* all_interfaces() { return kAll; }

size_t all_interface_count() { return sizeof(kAll) / sizeof(kAll[0]); }

} // namespace sdk::interfaces
