// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#pragma once

#include <cstddef>

#include "Interface.hpp"

namespace sdk::interfaces {

// One entry per interface INSTANCE recovered from FEAR2.exe
// (36 names across 30 interfaces).
//
// `get` and `agreement` call the generated per-interface class's own
// public getter, so iterating this table is a real test of the typed
// API rather than of the registry alone.
struct InterfaceEntry {
    const char* name;
    void* (*get)();
    Registry::Agreement (*agreement)();
};

const InterfaceEntry* all_interfaces();
size_t all_interface_count();

} // namespace sdk::interfaces
