// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "IClientShell.hpp"

namespace sdk::interfaces {

IClientShell* IClientShell::get() {
    return static_cast<IClientShell*>(resolve_interface(kName));
}

Registry::Agreement IClientShell::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
