// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ICommandLineArgs.hpp"

namespace sdk::interfaces {

ICommandLineArgs* ICommandLineArgs::get() {
    return static_cast<ICommandLineArgs*>(resolve_interface(kName));
}

Registry::Agreement ICommandLineArgs::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
