// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ICompress.hpp"

namespace sdk::interfaces {

ICompress* ICompress::get() {
    return static_cast<ICompress*>(resolve_interface(kName));
}

Registry::Agreement ICompress::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
