// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTCursor.hpp"

namespace sdk::interfaces {

ILTCursor* ILTCursor::get() {
    return static_cast<ILTCursor*>(resolve_interface(kName));
}

Registry::Agreement ILTCursor::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
