// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTClientContentTransfer.hpp"

namespace sdk::interfaces {

ILTClientContentTransfer* ILTClientContentTransfer::get() {
    return static_cast<ILTClientContentTransfer*>(resolve_interface(kName));
}

Registry::Agreement ILTClientContentTransfer::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
