// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTClient.hpp"

namespace sdk::interfaces {

ILTClient* ILTClient::get() {
    return static_cast<ILTClient*>(resolve_interface(kName));
}

Registry::Agreement ILTClient::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
