// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTCommon.hpp"

namespace sdk::interfaces {

ILTCommon* ILTCommon::get_client() {
    return static_cast<ILTCommon*>(resolve_interface(kNameClient));
}

Registry::Agreement ILTCommon::agreement_client() {
    return interface_agreement(kNameClient);
}

ILTCommon* ILTCommon::get_server() {
    return static_cast<ILTCommon*>(resolve_interface(kNameServer));
}

Registry::Agreement ILTCommon::agreement_server() {
    return interface_agreement(kNameServer);
}

} // namespace sdk::interfaces
