// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTCustomRender.hpp"

namespace sdk::interfaces {

ILTCustomRender* ILTCustomRender::get() {
    return static_cast<ILTCustomRender*>(resolve_interface(kName));
}

Registry::Agreement ILTCustomRender::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
