// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTDrawPrim.hpp"

namespace sdk::interfaces {

ILTDrawPrim* ILTDrawPrim::get() {
    return static_cast<ILTDrawPrim*>(resolve_interface(kName));
}

Registry::Agreement ILTDrawPrim::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
