// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTFileMgr.hpp"

namespace sdk::interfaces {

ILTFileMgr* ILTFileMgr::get() {
    return static_cast<ILTFileMgr*>(resolve_interface(kName));
}

Registry::Agreement ILTFileMgr::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
