// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTInput.hpp"

namespace sdk::interfaces {

ILTInput* ILTInput::get() {
    return static_cast<ILTInput*>(resolve_interface(kName));
}

Registry::Agreement ILTInput::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
