// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTLoadingProgress.hpp"

namespace sdk::interfaces {

ILTLoadingProgress* ILTLoadingProgress::get() {
    return static_cast<ILTLoadingProgress*>(resolve_interface(kName));
}

Registry::Agreement ILTLoadingProgress::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
