// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#pragma once

#include "Interface.hpp"

namespace sdk::interfaces {

// ILTModel -- engine instances: Client (3 holders), Server (4 holders).
//
// OPAQUE HANDLE. No fields, no methods: what is proven is this
// interface's engine-side NAME and the holder slots carrying its
// pointer, NOT any vtable layout or member offset. Adding a method
// requires reversing that vtable and mapping it in fear2.genny first
// (AGENT.MD 5a).
//
// A getter may return nullptr: the interface database fills slots via
// APIFound() and clears them via APIRemoved(), so null means "not
// resolved right now" (early startup, unloaded module), never
// "broken mapping". Null-check per use; never hold across a frame.
//
// ONE type, several instances: the instances share this interface's
// ABI, so they are getters rather than separate classes. A method
// added later is written once and works for every instance.
class ILTModel final {
public:
    static constexpr const char* kNameClient = "ILTModel.Client";
    static constexpr const char* kNameServer = "ILTModel.Server";

    static ILTModel* get_client();
    static ILTModel* get_server();

    static Registry::Agreement agreement_client();
    static Registry::Agreement agreement_server();

    // Engine-owned. Instances of this type only ever exist as a
    // reinterpreted engine pointer, so construction, destruction and
    // copying are all deleted: `ILTFoo x{};` would otherwise be a
    // meaningless empty object that looks like a real interface.
    ILTModel() = delete;
    ~ILTModel() = delete;
    ILTModel(const ILTModel&) = delete;
    ILTModel& operator=(const ILTModel&) = delete;
};

} // namespace sdk::interfaces
