// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTModel.hpp"

namespace sdk::interfaces {

ILTModel* ILTModel::get_client() {
    return static_cast<ILTModel*>(resolve_interface(kNameClient));
}

Registry::Agreement ILTModel::agreement_client() {
    return interface_agreement(kNameClient);
}

ILTModel* ILTModel::get_server() {
    return static_cast<ILTModel*>(resolve_interface(kNameServer));
}

Registry::Agreement ILTModel::agreement_server() {
    return interface_agreement(kNameServer);
}

} // namespace sdk::interfaces
