// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTPhysicsSim.hpp"

namespace sdk::interfaces {

ILTPhysicsSim* ILTPhysicsSim::get_client() {
    return static_cast<ILTPhysicsSim*>(resolve_interface(kNameClient));
}

Registry::Agreement ILTPhysicsSim::agreement_client() {
    return interface_agreement(kNameClient);
}

ILTPhysicsSim* ILTPhysicsSim::get_server() {
    return static_cast<ILTPhysicsSim*>(resolve_interface(kNameServer));
}

Registry::Agreement ILTPhysicsSim::agreement_server() {
    return interface_agreement(kNameServer);
}

} // namespace sdk::interfaces
