// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTPhysics.hpp"

namespace sdk::interfaces {

ILTPhysics* ILTPhysics::get_client() {
    return static_cast<ILTPhysics*>(resolve_interface(kNameClient));
}

Registry::Agreement ILTPhysics::agreement_client() {
    return interface_agreement(kNameClient);
}

ILTPhysics* ILTPhysics::get_server() {
    return static_cast<ILTPhysics*>(resolve_interface(kNameServer));
}

Registry::Agreement ILTPhysics::agreement_server() {
    return interface_agreement(kNameServer);
}

} // namespace sdk::interfaces
