// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTResourceMgr.hpp"

namespace sdk::interfaces {

ILTResourceMgr* ILTResourceMgr::get() {
    return static_cast<ILTResourceMgr*>(resolve_interface(kName));
}

Registry::Agreement ILTResourceMgr::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
