// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTRenderer.hpp"

namespace sdk::interfaces {

ILTRenderer* ILTRenderer::get() {
    return static_cast<ILTRenderer*>(resolve_interface(kName));
}

Registry::Agreement ILTRenderer::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
