// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#pragma once

#include "Interface.hpp"

namespace sdk::interfaces {

// ILTRenderer -- engine instances: Default (5 holders).
//
// OPAQUE HANDLE. No fields, no methods: what is proven is this
// interface's engine-side NAME and the holder slots carrying its
// pointer, NOT any vtable layout or member offset. Adding a method
// requires reversing that vtable and mapping it in fear2.genny first
// (AGENTS.md 5a).
//
// A getter may return nullptr: the interface database fills slots via
// APIFound() and clears them via APIRemoved(), so null means "not
// resolved right now" (early startup, unloaded module), never
// "broken mapping". Null-check per use; never hold across a frame.
class ILTRenderer final {
public:
    static constexpr const char* kName = "ILTRenderer.Default";

    static ILTRenderer* get();

    static Registry::Agreement agreement();

    // Engine-owned. Instances of this type only ever exist as a
    // reinterpreted engine pointer, so construction, destruction and
    // copying are all deleted: `ILTFoo x{};` would otherwise be a
    // meaningless empty object that looks like a real interface.
    ILTRenderer() = delete;
    ~ILTRenderer() = delete;
    ILTRenderer(const ILTRenderer&) = delete;
    ILTRenderer& operator=(const ILTRenderer&) = delete;
};

} // namespace sdk::interfaces
