// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#pragma once

#include "Interface.hpp"

namespace sdk::interfaces {

// ILTSoundMgr -- engine instances: Client (1 holder), Server (1 holder).
//
// OPAQUE HANDLE. No fields, no methods: what is proven is this
// interface's engine-side NAME and the holder slots carrying its
// pointer, NOT any vtable layout or member offset. Adding a method
// requires reversing that vtable and mapping it in fear2.genny first
// (AGENTS.md 5a).
//
// A getter may return nullptr: the interface database fills slots via
// APIFound() and clears them via APIRemoved(), so null means "not
// resolved right now" (early startup, unloaded module), never
// "broken mapping". Null-check per use; never hold across a frame.
//
// ONE type, several instances: the instances share this interface's
// ABI, so they are getters rather than separate classes. A method
// added later is written once and works for every instance.
class ILTSoundMgr final {
public:
    static constexpr const char* kNameClient = "ILTSoundMgr.Client";
    static constexpr const char* kNameServer = "ILTSoundMgr.Server";

    static ILTSoundMgr* get_client();
    static ILTSoundMgr* get_server();

    static Registry::Agreement agreement_client();
    static Registry::Agreement agreement_server();

    // Engine-owned. Instances of this type only ever exist as a
    // reinterpreted engine pointer, so construction, destruction and
    // copying are all deleted: `ILTFoo x{};` would otherwise be a
    // meaningless empty object that looks like a real interface.
    ILTSoundMgr() = delete;
    ~ILTSoundMgr() = delete;
    ILTSoundMgr(const ILTSoundMgr&) = delete;
    ILTSoundMgr& operator=(const ILTSoundMgr&) = delete;
};

} // namespace sdk::interfaces
