// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTSoundMgr.hpp"

namespace sdk::interfaces {

ILTSoundMgr* ILTSoundMgr::get_client() {
    return static_cast<ILTSoundMgr*>(resolve_interface(kNameClient));
}

Registry::Agreement ILTSoundMgr::agreement_client() {
    return interface_agreement(kNameClient);
}

ILTSoundMgr* ILTSoundMgr::get_server() {
    return static_cast<ILTSoundMgr*>(resolve_interface(kNameServer));
}

Registry::Agreement ILTSoundMgr::agreement_server() {
    return interface_agreement(kNameServer);
}

} // namespace sdk::interfaces
