// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTServerContentTransfer.hpp"

namespace sdk::interfaces {

ILTServerContentTransfer* ILTServerContentTransfer::get() {
    return static_cast<ILTServerContentTransfer*>(resolve_interface(kName));
}

Registry::Agreement ILTServerContentTransfer::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
