// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTServer.hpp"

namespace sdk::interfaces {

ILTServer* ILTServer::get() {
    return static_cast<ILTServer*>(resolve_interface(kName));
}

Registry::Agreement ILTServer::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
