// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTTimer.hpp"

namespace sdk::interfaces {

ILTTimer* ILTTimer::get_client() {
    return static_cast<ILTTimer*>(resolve_interface(kNameClient));
}

Registry::Agreement ILTTimer::agreement_client() {
    return interface_agreement(kNameClient);
}

ILTTimer* ILTTimer::get_server() {
    return static_cast<ILTTimer*>(resolve_interface(kNameServer));
}

Registry::Agreement ILTTimer::agreement_server() {
    return interface_agreement(kNameServer);
}

} // namespace sdk::interfaces
