// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTTextureString.hpp"

namespace sdk::interfaces {

ILTTextureString* ILTTextureString::get() {
    return static_cast<ILTTextureString*>(resolve_interface(kName));
}

Registry::Agreement ILTTextureString::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
