// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTTextureMgr.hpp"

namespace sdk::interfaces {

ILTTextureMgr* ILTTextureMgr::get() {
    return static_cast<ILTTextureMgr*>(resolve_interface(kName));
}

Registry::Agreement ILTTextureMgr::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
