// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTUI.hpp"

namespace sdk::interfaces {

ILTUI* ILTUI::get() {
    return static_cast<ILTUI*>(resolve_interface(kName));
}

Registry::Agreement ILTUI::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
