// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "ILTVideoTexture.hpp"

namespace sdk::interfaces {

ILTVideoTexture* ILTVideoTexture::get() {
    return static_cast<ILTVideoTexture*>(resolve_interface(kName));
}

Registry::Agreement ILTVideoTexture::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
