#pragma once

#include "Registry.hpp"

namespace sdk::interfaces {

// Shared plumbing behind every per-interface class.
//
// Each interface gets its own header/source pair (generated by
// reversing/gen_interfaces.py from reversing/interfaces.txt). Those classes are
// deliberately thin: they carry the engine-side name and forward to these two
// helpers, so the actual lookup exists exactly once rather than 36 times.
//
// WHAT resolve_interface() DOES AND DOES NOT PROMISE
//
// It returns the engine's live interface pointer, or nullptr. It is
// deliberately NOT cached: FEAR2's interface database fills a holder's slot via
// APIFound() and clears it via APIRemoved(), so a pointer valid now can be null
// after a module unload. Every call re-reads the slot.
//
// nullptr therefore means "not resolved right now", which is entirely normal:
//   - before CInterfaceDatabase has resolved modules (early startup),
//   - for server-side interfaces while no server is running,
//   - after the owning module is unloaded.
// It is NOT evidence of a broken mapping. Callers must null-check per use and
// must not hold the pointer across a frame boundary.
//
// THE INTERFACE TYPES ARE OPAQUE HANDLES, NOT LAYOUTS.
//
// The generated classes are empty by design: no fields, no methods. What is
// proven is each interface's NAME and the holder slots carrying its pointer --
// not any vtable or member offset. Adding a method requires reversing that
// vtable and mapping it in reversing/fear2.genny first (AGENT.MD 5a). Until
// then a typed handle is exactly as much as the evidence supports: it buys
// type-distinct plumbing without inventing structure.

// Current pointer for `name`, or nullptr. Initializes the registry on first
// use, and retries if an earlier attempt was too early to succeed.
void* resolve_interface(const char* name);

// Holder bookkeeping for `name`: how many holders requested it, how many slots
// currently hold a pointer, and whether those agree.
//
// total > 1 is EXPECTED, not a bug: define_holder is emitted per translation
// unit, so one interface has many holders (ILTClient has 14), each with its own
// slot. all_agree being false would be the real anomaly.
Registry::Agreement interface_agreement(const char* name);

} // namespace sdk::interfaces
