#pragma once

#include <string>

#include <optional>

#include "Registry.hpp"

namespace sdk::interfaces {

// Shared plumbing behind every per-interface class.
//
// Each interface gets its own header/source pair (generated by
// reversing/gen_interfaces.py from reversing/interfaces.txt). Those classes are
// deliberately thin: they carry the engine-side name and forward to these two
// helpers, so the actual lookup exists exactly once rather than 36 times.
//
// WHAT resolve_interface() DOES AND DOES NOT PROMISE
//
// It returns the engine's live interface pointer, or nullptr. It is
// deliberately NOT cached: FEAR2's interface database fills a holder's slot via
// APIFound() and clears it via APIRemoved(), so a pointer valid now can be null
// after a module unload. Every call re-reads the slot.
//
// nullptr therefore means "not resolved right now", which is entirely normal:
//   - before CInterfaceDatabase has resolved modules (early startup),
//   - for server-side interfaces while no server is running,
//   - after the owning module is unloaded.
// It is NOT evidence of a broken mapping. Callers must null-check per use and
// must not hold the pointer across a frame boundary.
//
// THE INTERFACE TYPES ARE OPAQUE HANDLES, NOT LAYOUTS.
//
// The generated classes are empty by design: no fields, no methods. What is
// proven is each interface's NAME and the holder slots carrying its pointer --
// not any vtable or member offset. Adding a method requires reversing that
// vtable and mapping it in reversing/fear2.genny first (AGENT.MD 5a). Until
// then a typed handle is exactly as much as the evidence supports: it buys
// type-distinct plumbing without inventing structure.

// Current pointer for `name`, or nullptr. Initializes the registry on first
// use, and retries if an earlier attempt was too early to succeed.
void* resolve_interface(const char* name);

// NAMED FOR THE OBSERVATION, NOT THE MEANING. This reports a string found in a particular instruction
// shape at vtable slot 1; it cannot prove what that slot MEANS. On the interfaces checked the shape sits
// on IBase::_InterfaceImplementation, so the string is the implementing class's name for itself
// ("CLTClient", "CLTModelClient", "CLTTextureMgr") -- but that is an observation about those objects,
// not a property this function establishes.
//
// The literal named by `iface`'s vtable slot 1, when that slot's ENTRY SEQUENCE is
//
//     B8 <imm32>   mov eax, <string address>
//     C3           retn
//
// and nullopt otherwise. Six bytes is an entry sequence, NOT the function's extent: unreachable bytes
// or another label may follow, and nothing here measures where the body ends. A consumer can use the
// string to confirm a resolved pointer really is the class expected.
//
// The address must lie on an EXECUTABLE, non-guard page before any byte is read, so a data pointer that
// happens to begin with 0xB8 cannot be mistaken for a function body, and a guard page is never touched
// (reading one would clear the guard -- a real side effect).
//
// IT DOES NOT CALL THE SLOT. The string address is read out of the instruction's immediate and
// dereferenced directly, so safety does not rest on knowing the function's extent at all. Even taken as
// a callable, an entry sequence that loads a constant and returns cannot reach whatever follows it; but
// nothing here is invoked, so the question does not arise.
//
// IT CLAIMS NOTHING ABOUT LAYOUT. This is NOT an assertion that every interface carries
// _InterfaceImplementation at slot 1; it was verified for a handful, not for all of them. The check is
// per object and per call: either this object's slot 1 has the constant-return shape, in which case the
// string is what that body returns, or it does not and you get nullopt. A differently laid-out
// interface fails the shape test rather than being misread.
std::optional<std::string> slot1_constant_string(void* iface);

// Holder bookkeeping for `name`: how many holders requested it, how many slots
// currently hold a pointer, and whether those agree.
//
// total > 1 is EXPECTED, not a bug: define_holder is emitted per translation
// unit, so one interface has many holders (ILTClient has 14), each with its own
// slot. all_agree being false would be the real anomaly.
Registry::Agreement interface_agreement(const char* name);

} // namespace sdk::interfaces
