// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "IServerShell.hpp"

namespace sdk::interfaces {

IServerShell* IServerShell::get() {
    return static_cast<IServerShell*>(resolve_interface(kName));
}

Registry::Agreement IServerShell::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
