// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "IServerConsoleState.hpp"

namespace sdk::interfaces {

IServerConsoleState* IServerConsoleState::get() {
    return static_cast<IServerConsoleState*>(resolve_interface(kName));
}

Registry::Agreement IServerConsoleState::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
