// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "IWorldClientBSP.hpp"

namespace sdk::interfaces {

IWorldClientBSP* IWorldClientBSP::get() {
    return static_cast<IWorldClientBSP*>(resolve_interface(kName));
}

Registry::Agreement IWorldClientBSP::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
