// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "IWorldParticleBlockerData.hpp"

namespace sdk::interfaces {

IWorldParticleBlockerData* IWorldParticleBlockerData::get() {
    return static_cast<IWorldParticleBlockerData*>(resolve_interface(kName));
}

Registry::Agreement IWorldParticleBlockerData::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
