// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.
// Edit reversing/interfaces.txt and regenerate.

#include "IWorldServerBSP.hpp"

namespace sdk::interfaces {

IWorldServerBSP* IWorldServerBSP::get() {
    return static_cast<IWorldServerBSP*>(resolve_interface(kName));
}

Registry::Agreement IWorldServerBSP::agreement() {
    return interface_agreement(kName);
}

} // namespace sdk::interfaces
