#!/usr/bin/env python3
"""Generate shared/sdk/interfaces/<Interface>.{hpp,cpp} from interfaces.txt.

Input  : reversing/interfaces.txt  -- "<Interface>.<Instance> <holder count>"
Output : one header/source pair per INTERFACE (not per instance), plus
         All.hpp/All.cpp aggregating every name for diagnostics and tests.

Run from the repo root:  python reversing/gen_interfaces.py

Why generated: the 30 classes are pure boilerplate over one shared lookup, and
the set is derived evidence (recovered from CAPIHolder call sites -- see
INTERFACE_HOLDERS.md). Regenerating keeps them consistent and makes the diff of
a re-reversing pass reviewable as a change to interfaces.txt.

Why one class per interface, several getters: `.Default` / `.Client` / `.Server`
are INSTANCE names of the same interface, which has one ABI. Splitting
ILTModel.Client and ILTModel.Server into unrelated C++ types would duplicate
every method once its vtable is reversed, and would make two pointers to the
same interface mutually incompatible.
"""

import os
import sys
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIST = os.path.join(ROOT, "reversing", "interfaces.txt")
OUT = os.path.join(ROOT, "shared", "sdk", "interfaces")

BANNER = "// GENERATED by reversing/gen_interfaces.py -- do not edit by hand.\n" \
         "// Edit reversing/interfaces.txt and regenerate.\n"


def load():
    """interface -> OrderedDict(instance -> holder count)"""
    ifaces = OrderedDict()
    with open(LIST, "r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            name, count = parts[0], int(parts[1]) if len(parts) > 1 else 0
            if "." not in name:
                raise SystemExit(f"malformed entry (need Interface.Instance): {line!r}")
            iface, inst = name.split(".", 1)
            ifaces.setdefault(iface, OrderedDict())[inst] = count
    return ifaces


def getter(inst):
    return "get" if inst == "Default" else "get_" + inst.lower()


def agree(inst):
    return "agreement" if inst == "Default" else "agreement_" + inst.lower()


def const(inst):
    return "kName" if inst == "Default" else "kName" + inst


def header(iface, instances):
    total = sum(instances.values())
    plural = "" if total == 1 else "s"
    inst_doc = ", ".join(f"{i} ({n} holder{'' if n == 1 else 's'})"
                         for i, n in instances.items())
    lines = [BANNER, "#pragma once", "", '#include "Interface.hpp"', "",
             "namespace sdk::interfaces {", ""]
    lines += [
        f"// {iface} -- engine instance{plural}: {inst_doc}.",
        "//",
        "// OPAQUE HANDLE. No fields, no methods: what is proven is this",
        "// interface's engine-side NAME and the holder slots carrying its",
        "// pointer, NOT any vtable layout or member offset. Adding a method",
        "// requires reversing that vtable and mapping it in fear2.genny first",
        "// (AGENT.MD 5a).",
        "//",
        "// A getter may return nullptr: the interface database fills slots via",
        "// APIFound() and clears them via APIRemoved(), so null means \"not",
        "// resolved right now\" (early startup, unloaded module), never",
        "// \"broken mapping\". Null-check per use; never hold across a frame.",
    ]
    if len(instances) > 1:
        lines += [
            "//",
            "// ONE type, several instances: the instances share this interface's",
            "// ABI, so they are getters rather than separate classes. A method",
            "// added later is written once and works for every instance.",
        ]
    lines += [f"class {iface} final {{", "public:"]
    for inst in instances:
        lines.append(f'    static constexpr const char* {const(inst)} = "{iface}.{inst}";')
    lines.append("")
    for inst in instances:
        lines.append(f"    static {iface}* {getter(inst)}();")
    lines.append("")
    for inst in instances:
        lines.append(f"    static Registry::Agreement {agree(inst)}();")
    lines += [
        "",
        "    // Engine-owned. Instances of this type only ever exist as a",
        "    // reinterpreted engine pointer, so construction, destruction and",
        "    // copying are all deleted: `ILTFoo x{};` would otherwise be a",
        "    // meaningless empty object that looks like a real interface.",
        f"    {iface}() = delete;",
        f"    ~{iface}() = delete;",
        f"    {iface}(const {iface}&) = delete;",
        f"    {iface}& operator=(const {iface}&) = delete;",
        "};",
        "",
        "} // namespace sdk::interfaces",
        "",
    ]
    return "\n".join(lines)


def source(iface, instances):
    lines = [BANNER, f'#include "{iface}.hpp"', "", "namespace sdk::interfaces {", ""]
    for inst in instances:
        lines += [
            f"{iface}* {iface}::{getter(inst)}() {{",
            f"    return static_cast<{iface}*>(resolve_interface({const(inst)}));",
            "}",
            "",
            f"Registry::Agreement {iface}::{agree(inst)}() {{",
            f"    return interface_agreement({const(inst)});",
            "}",
            "",
        ]
    lines += ["} // namespace sdk::interfaces", ""]
    return "\n".join(lines)


def aggregate(ifaces):
    """All.hpp/All.cpp -- a descriptor table of TYPED getters.

    Deliberately routes through each generated class's own public getter rather
    than calling Registry::agreement(name) directly. Diagnostics and tests that
    walk this table therefore exercise all 36 real API paths, so a miswired
    kName constant or a getter bound to the wrong instance is caught instead of
    being masked by a registry lookup that happens to use the right string.
    """
    pairs = [(i, inst) for i, insts in ifaces.items() for inst in insts]
    pairs.sort(key=lambda p: f"{p[0]}.{p[1]}")

    hpp = [BANNER, "#pragma once", "", "#include <cstddef>", "",
           '#include "Interface.hpp"', "", "namespace sdk::interfaces {", "",
           "// One entry per interface INSTANCE recovered from FEAR2.exe",
           f"// ({len(pairs)} names across {len(ifaces)} interfaces).",
           "//",
           "// `get` and `agreement` call the generated per-interface class's own",
           "// public getter, so iterating this table is a real test of the typed",
           "// API rather than of the registry alone.",
           "struct InterfaceEntry {",
           "    const char* name;",
           "    void* (*get)();",
           "    Registry::Agreement (*agreement)();",
           "};", "",
           "const InterfaceEntry* all_interfaces();",
           "size_t all_interface_count();", "",
           "} // namespace sdk::interfaces", ""]

    cpp = [BANNER, '#include "All.hpp"', ""]
    for iface in ifaces:
        cpp.append(f'#include "{iface}.hpp"')
    cpp += ["", "namespace sdk::interfaces {", "", "namespace {", ""]
    for iface, inst in pairs:
        tag = f"{iface}_{inst}"
        cpp += [
            f"void* get_{tag}() {{ return {iface}::{getter(inst)}(); }}",
            f"Registry::Agreement agree_{tag}() {{ return {iface}::{agree(inst)}(); }}",
            "",
        ]
    cpp.append("const InterfaceEntry kAll[] = {")
    for iface, inst in pairs:
        tag = f"{iface}_{inst}"
        cpp.append(f'    {{"{iface}.{inst}", &get_{tag}, &agree_{tag}}},')
    cpp += ["};", "", "} // namespace", "",
            "const InterfaceEntry* all_interfaces() { return kAll; }", "",
            "size_t all_interface_count() { return sizeof(kAll) / sizeof(kAll[0]); }", "",
            "} // namespace sdk::interfaces", ""]
    return "\n".join(hpp), "\n".join(cpp)


def main():
    ifaces = load()
    os.makedirs(OUT, exist_ok=True)
    written = 0
    for iface, instances in ifaces.items():
        for path, text in ((f"{iface}.hpp", header(iface, instances)),
                           (f"{iface}.cpp", source(iface, instances))):
            with open(os.path.join(OUT, path), "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
            written += 1
    hpp, cpp = aggregate(ifaces)
    for path, text in (("All.hpp", hpp), ("All.cpp", cpp)):
        with open(os.path.join(OUT, path), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        written += 1
    total_names = sum(len(v) for v in ifaces.values())
    print(f"{len(ifaces)} interfaces / {total_names} names -> {written} files in {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
